CREATE DATABASE SOCIAL_MEDIA_PLATFORM;
GO
USE SOCIAL_MEDIA_PLATFORM;
GO

CREATE TABLE USERS (
    ID INT IDENTITY PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    DATE_OF_BIRTH varchar NOT NULL,
    JOIN_DATE DATETIME DEFAULT GETUTCDATE()
);
CREATE TABLE POST (
    ID INT IDENTITY PRIMARY KEY,
    USERS_ID INT NOT NULL,
    CONTENT NVARCHAR(MAX) NOT NULL,
    POST_DATE DATETIME DEFAULT GETUTCDATE(),
    VISIBL_STATE VARCHAR(50) CHECK (VISIBL_STATE IN ('VISIBLE', 'NOT VISIBLE')) DEFAULT 'VISIBLE',
    FOREIGN KEY (USERS_ID) REFERENCES USERS(ID)
);

CREATE TABLE INTERACTION (
    ID INT IDENTITY PRIMARY KEY,
    POST_ID INT NOT NULL,
    USERS_ID INT NOT NULL,
    TYPE NVARCHAR(50),
    INTERACTION_DATE DATETIME DEFAULT GETUTCDATE(),
    FOREIGN KEY (USERS_ID) REFERENCES USERS(ID),
    FOREIGN KEY (POST_ID) REFERENCES POST(ID)
);

CREATE TABLE COMMENTS (
    ID INT IDENTITY PRIMARY KEY,
    USERS_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    CONTENT NVARCHAR(max) NOT NULL,
    COMMENT_DATE DATETIME DEFAULT GETUTCDATE(),
    FOREIGN KEY (USERS_ID) REFERENCES USERS(ID),
    FOREIGN KEY (POST_ID) REFERENCES POST(ID)
);

INSERT INTO USERS (EMAIL, DATE_OF_BIRTH, JOIN_DATE)
VALUES
('mostafa@example.com', '2004-03-22', GETUTCDATE()),
('aboelmakarim@example.com', '2004-03-22', GETUTCDATE());

INSERT INTO POST (USERS_ID, CONTENT, POST_DATE)
VALUES
(10, 'my name is mostafa', GETUTCDATE()),
(11, 'surprise mother father', GETUTCDATE());


INSERT INTO INTERACTION (POST_ID, USERS_ID, TYPE, INTERACTION_DATE)
VALUES
(4, 10, 'LIKE', GETUTCDATE()),  

INSERT INTO COMMENTS (USERS_ID, POST_ID, CONTENT, COMMENT_DATE)
VALUES
(10, 4, 'alazhar gdcg', GETUTCDATE()),  
(11, 5, 'Traveling is awesome!', GETUTCDATE()); 

select * from users
select * from post
select * from INTERACTION
select * from COMMENTS



DROP TABLE USERS;
DROP DATABASE SOCIAL_MEDIA_PLATFORM;